### PR TITLE
internal functions in dedicated file, function to add visit labels, availability of meta tables added to study.options

### PR DESCRIPTION
**Pull request by aghaynes**

### CODE REVIEW

**Comment by aghaynes** [comment]
I just added a variety of other changes. Most important/useful is perhaps .factorize, which could be integrated into read.DB

**Comment by PatrickRWright** [comment]
Hi Alan, I merged your changes in my fork and the test related to the rectangular data is failing. I think this is related to the short version (filename) of the visitplan in the rectangular format is not only vp.xls. In the test case its vp_DEM00.xls.

**Comment by PatrickRWright** [comment]
Maybe .constructmetaname should build a regex (e.g. "vp.*\\.xls") and check for this?

**Comment by aghaynes** [comment]
I used ExportOption because it's always there. I don't think the same can be said of vp (it's not there unless you select to export the system setup, or something similar, if i remember correctly). I originally wanted to use something to compare all of the files to identify the substring, but couldn't think of a good solution that way.

**Comment by aghaynes** [comment]
i extended study.options a bit more. the names of the files are now defined in there. There is also a named data.names object within study.options so that it's possible to compare the new name and the old one.
tests all pass

**Comment by PatrickRWright** [comment]
Thank you @aghaynes

**Comment by aghaynes** [comment]
Thank you @PatrickRWright

**Pull request merged**
