### PR TITLE
new load.study.options

### PR DESCRIPTION
**Pull request by aghaynes**
load.study.options now gleans info from data.dir. It cannot be called after loading the package anymore.
long names are now shortened (it works with our settings...hopefully they're general enough...) so the warning could be removed perhaps.
Better support for short or long names (this produced error previously due to use of cn and ctr) 

output....
** Checking for 'Column names' in ExportOptions.html'
** 'Column names' ('Spaltennamen') was found in ExportOptions.html
** Checking for 'Add-ID' in ExportOptions.html
** 'Add-ID' ('Zus-ID', 'Patient-ID') was found in ExportOptions.html
** Loading all tables from p_export_CSV-xls_P0640_20181129-115005.zip
** Ensuring that no 'table.list' was set by user
--- Deleting previous 'table.list'
** Building the 'table.list'
*** 31 tables were found
** Calling load.tables(data.dir, tables = table.list, ...)
** Checking for 'Column names' in ExportOptions.html'
** 'Column names' ('Spaltennamen') was found in ExportOptions.html
** Checking for 'Add-ID' in ExportOptions.html
** 'Add-ID' ('Zus-ID', 'Patient-ID') was found in ExportOptions.html
** Loading tables as defined in input tables = ... 
*** Added cn.xls to tables
--- table ExportOptions_P0640_20181129-115005.html loaded as ExportOptions.html ---
--- table visitplan_P0640_20181129-115005.xls loaded as visitplan ---
--- table visitplanforms_P0640_20181129-115005.xls loaded as visitplanforms ---
--- table forms_P0640_20181129-115005.xls loaded as forms ---
--- table questions_P0640_20181129-115005.xls loaded as questions ---
--- table items_P0640_20181129-115005.xls loaded as items ---
--- table centres_P0640_20181129-115005.xls loaded as centres ---
--- table casenodes_P0640_20181129-115005.xls loaded as patient ---
--- table mnpp0640_eligibility_P0640_20181129-115005.xls loaded as eligibility ---
--- table mnpp0640_rando_P0640_20181129-115005.xls loaded as rando ---
--- table mnpp0640_vdata_P0640_20181129-115005.xls loaded as vdata ---
--- table mnpp0640_aespec_P0640_20181129-115005.xls loaded as aespec ---
--- table mnpp0640_mh_P0640_20181129-115005.xls loaded as mh ---
--- table mnpp0640_pe_P0640_20181129-115005.xls loaded as pe ---
--- table mnpp0640_lab_blood_P0640_20181129-115005.xls loaded as lab_blood ---
--- table mnpp0640_lab_urine_P0640_20181129-115005.xls loaded as lab_urine ---
--- table mnpp0640_eos_P0640_20181129-115005.xls loaded as eos ---
--- table mnpp0640_cm_P0640_20181129-115005.xls loaded as cm ---
--- table mnpp0640_stone_P0640_20181129-115005.xls loaded as stone ---
--- table mnpp0640_ct_P0640_20181129-115005.xls loaded as ct ---
--- table mnpp0640_drugdisp_P0640_20181129-115005.xls loaded as drugdisp ---
--- table mnpp0640_admin_P0640_20181129-115005.xls loaded as admin ---
--- table mnpp0640_sae_P0640_20181129-115005.xls loaded as sae ---
--- table mnpp0640_saepi_P0640_20181129-115005.xls loaded as saepi ---
--- table emnpp0640_mh_oth_P0640_20181129-115005.xls loaded as e_mh_oth ---
--- table emnpp0640_cm_P0640_20181129-115005.xls loaded as e_cm ---
--- table emnpp0640_stone_sub1_P0640_20181129-115005.xls loaded as e_stone_sub1 ---
--- table emnpp0640_ct_sub_P0640_20181129-115005.xls loaded as e_ct_sub ---
--- table emnpp0640_drugdisp_P0640_20181129-115005.xls loaded as e_drugdisp ---
--- table emnpp0640_admin_P0640_20181129-115005.xls loaded as e_admin ---
--- table cl_P0640_20181129-115005.xls loaded as cl ---
Warning messages:
1: In while (codeCount + newLen > length(codeBuf)) { :
  closing unused connection 8 (p_export_CSV-xls_P0640_20181129-115005.zip:ExportOptions_P0640_20181129-115005.html)
2: In while (codeCount + newLen > length(codeBuf)) { :
  closing unused connection 7 (p_export_CSV-xls_P0640_20181129-115005.zip:visitplan_P0640_20181129-115005.xls)
3: In while (codeCount + newLen > length(codeBuf)) { :
  closing unused connection 6 (p_export_CSV-xls_P0640_20181129-115005.zip:ExportOptions_P0640_20181129-115005.html)
4: In while (codeCount + newLen > length(codeBuf)) { :
  closing unused connection 5 (p_export_CSV-xls_P0640_20181129-115005.zip:visitplan_P0640_20181129-115005.xls)
5: In while (codeCount + newLen > length(codeBuf)) { :
  closing unused connection 4 (p_export_CSV-xls_P0640_20181129-115005.zip:ExportOptions_P0640_20181129-115005.html)
6: In load.tables(data.dir) :
  The export option 'shorten table names' has not been enables which results in large data.frame names.
7: In load.tables(data.dir) :
  previously defined 'table.list' (possibly from dossier library) was written over!

8: In load.tables(data.dir, table.list, convert.dates, convert.unknown.date.to.na,  :
  The export option 'shorten table names' has not been enables which results in large data.frame names.
9: In load.tables(data.dir, table.list, convert.dates, convert.unknown.date.to.na,  :
  --- table casenodes_P0640_20181129-115005xls not found in p_export_CSV-xls_P0640_20181129-115005.zip
10: In tryCatchList(expr, classes, parentenv, handlers) :
  closing unused connection 7 (p_export_CSV-xls_P0640_20181129-115005.zip:visitplan_P0640_20181129-115005.xls)
11: In tryCatchList(expr, classes, parentenv, handlers) :
  closing unused connection 6 (p_export_CSV-xls_P0640_20181129-115005.zip:ExportOptions_P0640_20181129-115005.html)
12: In tryCatchList(expr, classes, parentenv, handlers) :
  closing unused connection 5 (p_export_CSV-xls_P0640_20181129-115005.zip:visitplan_P0640_20181129-115005.xls)
13: In tryCatchList(expr, classes, parentenv, handlers) :
  closing unused connection 4 (p_export_CSV-xls_P0640_20181129-115005.zip:ExportOptions_P0640_20181129-115005.html)

### CODE REVIEW

**Comment by DrEspresso** [comment]
Wow, this is so exciting to see you working on this study options. Something I planned ages ago but never found time to do it! Thanks!

**Comment by benkertp** [comment]
Dear Alan
Thanks a lot for your valuable feedback and the pull-request! I will integrate it by end of this week.
Pascal

**Comment by aghaynes** [comment]
I added a few more things.
- a couple of small (hidden) helper functions (one to remove project name - mnpXYZ - from text strings .removeproj(), and one to make pasting metadata file names together easier .constructmetaname()) 
- use the hidden functions in the appropriates places of load.tables
- new function to load a named vector of variable labels

**Comment by PatrickRWright** [comment]
Hi Alan,

thanks for the contribution. As you may have seen I have now added some testing with testthat and checked everything previous to merging your changes (test are passing as expected). I then pulled the changes from your repo into my fork and all the tests are passing so "high five" on that.

There are a few warnings though that only occur with your updates (can we avoid these?):
```
1: In exists(name, setterInlineHandlers, inherits = FALSE) :
  closing unused connection 5 (/home/wrightp/DM_secuTrial_R/inst/extdata/s_export_CSV-xls_DEM00_20180912-125720.zip:vp.xls)
2: In exists(name, setterInlineHandlers, inherits = FALSE) :
  closing unused connection 4 (/home/wrightp/DM_secuTrial_R/inst/extdata/s_export_CSV-xls_DEM00_20180912-125720.zip:ExportOptions.html)
3: In constantFoldCall(e, cntxt) :
  closing unused connection 4 (/home/wrightp/DM_secuTrial_R/inst/extdata/s_export_CSV-xls_DEM00_20180912-125720.zip:vp.xls)
4: In constantFoldCall(e, cntxt) :
  closing unused connection 3 (/home/wrightp/DM_secuTrial_R/inst/extdata/s_export_CSV-xls_DEM00_20180912-125720.zip:ExportOptions.html)
5: closing unused connection 4 (/home/wrightp/DM_secuTrial_R/inst/extdata/s_export_rt-CSV-xls_DEM00_20181016-151332.zip:vp_DEM00.xls) 
6: closing unused connection 3 (/home/wrightp/DM_secuTrial_R/inst/extdata/s_export_rt-CSV-xls_DEM00_20181016-151332.zip:ExportOptions.html)
```

**Comment by aghaynes** [comment]
I guess that comes from the use of unz in load.study.options.... I'll have a look...

**Comment by PatrickRWright** [comment]
I think you can close the file handle "somehow". I know this comment is probably not very helpful, but who knows.

**Comment by benkertp** [comment]
Dear Alan
I had a look at your pull-request.
Thanks a lot: very well done and very valuable! I especially liked your idea to pack all relevant "meta data" into the study options and the access to the labels (since we always use the decoded export we unfortunately do not have access to the codebook for the levels. something we can discuss in future). I also agree that initialising the study options while attaching the package is not very elegant and doing that in load.all.tables() makes more sense. The original idea was, to initialise the study-options early but allow them to be adapted (e.g. to accept more dates formats or by changing to way "incomplete dates" are processed. Until now I almost never changed the default.
But we can later handle that by providing additional arguments to the functions. 

Nice collaboration!

Pascal

**Comment by aghaynes** [comment]
Thanks Pascal.

Regarding the file connection, i think it's just a case of making 3 lines
(create the connection, load the data and close the connection) to do it
instead of one (create connection and load the data simultaneously)...

Regarding the labels, if the functions are all separate (as I've done with
load.labels) then the export format isn't so important (we can return a
warning that that type of metadata isn't available). That's another point
for the load.study.options... maybe we should add indicators for the
presence of the various metadata types. I also want to provide some
handling for factors, the info for which is also only available for
particular export types (another reason for expanding on the metadata
field).

For adapting the study.options, we could perhaps allow the study.options to
be submitted as an option to load.tables so that it could be set up first
with any additional parameters/formats. If there's nothing submitted, it
creates it, otherwise it uses the submitted version... should be reasonably
easy, although we might need to implement something to validate the
submitted version (or have an edit.study.options function?).

:) I like this! It's good fun! :)

**Comment by PatrickRWright** [comment]
Hi @aghaynes 

can you add the lines to close the file connetions to the pull request before I merge? If you're busy I can also figure out how to do that next week.

Cheers,
Patrick

**Comment by PatrickRWright** [comment]
Ok, great. I just checked and all tests are passing so I'll merge it now.

Thank you @aghaynes

**Pull request merged**
